### ISSUE TITLE
Empty token error

### ISSUE THREAD

**Issue by ozerovandrei** [serboox/os-cli#2]
Hello.

For some reason I'm getting the following error when I try to run the `create` command:
```
root@devstack:~# os-cli create --instName test --imageRef bb129fe1-ec15-4803-8565-f10d66c2d45a --flavorRef 1 --login demo --pass secret --auth-host http://10.10.0.101/identity
Token not be empty
```

All provided data is valid and I can get it via the standard `openstack` cli.

**Comment by serboox** [comment]
Hi, yes you will get this error if you use short --auth-host. You need use full URL for --auth-host, by example --auth-host http://10.10.0.101/identity/v3/auth/tokens
